name: Simple DevSecOps Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ------------------------
      # 1. Setup Python & Install Dependencies
      # ------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # ------------------------
      # 2. Run Unit Tests
      # ------------------------
      - name: Run tests
        run: pytest

      # ------------------------
      # 3. SAST (basic with Flake8)
      # ------------------------
      - name: Run Flake8 SAST
        run: flake8 .

      # ------------------------
      # 4. Build Docker Image
      # ------------------------
      - name: Build Docker image
        run: docker build -t devsecops-simple .

      # ------------------------
      # 5. Trivy Scan (Dependencies + Image)
      # ------------------------
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/trivy_0.68.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.68.2_Linux-64bit.deb

      - name: Run Trivy scan
        run: trivy image devsecops-simple --severity HIGH,CRITICAL
